### PR TITLE
LRCI-795 Fix subrepo integration error (TEST)

### PR DESCRIPTION
**Pull request by yichenroy**
https://issues.liferay.com/browse/LRCI-795

This is just a test PR.

### CODE REVIEW

**Comment by brianwulbern** [comment]
@yichenroy looks like that fixed it?

**Comment by yichenroy** [comment]
ci:test

Testing to see if the resolved requirements came from upstream.

**Comment by brianwulbern** [comment]
ci:test

**Comment by brianwulbern** [comment]
@yichenroy the change [here](https://github.com/pyoo47/liferay-jenkins-ee/pull/1293) got merged, so I'm trying again.

**Comment by brianwulbern** [comment]
ci:test

**Pull request closed without merging**
